
avanzu_admin_profile:
  path: /profile/{ident}/
  options:
    avanzu_admin_route: profile

avanzu_admin_logout:
  path: /logout
  options:
    avanzu_admin_route: logout

avanzu_admin_all_tasks:
  path: /tasks/
  options:
      avanzu_admin_route: all_tasks

avanzu_admin_show_task:
  path: /tasks/{ident}/
  options:
      avanzu_admin_route: task

avanzu_admin_all_notifications:
  path: /notifications/
  options:
      avanzu_admin_route: all_notifications

avanzu_admin_show_notification:
  path: /notifications/{ident}/
  options:
      avanzu_admin_route: notification

avanzu_admin_all_messages:
  path: /messages/
  options:
      avanzu_admin_route: all_messages

avanzu_admin_show_message:
  path: /messages/{ident}/
  options:
      avanzu_admin_route: message
