services:

    KevinPapst\AdminLTEBundle\Twig\AdminExtension:
        class: KevinPapst\AdminLTEBundle\Twig\AdminExtension
        arguments:
            - '@admin_lte_theme.context_helper'
            - '%admin_lte_theme.routes%'
        tags:
            - { name: twig.extension }

    KevinPapst\AdminLTEBundle\Helper\ContextHelper:
        class: KevinPapst\AdminLTEBundle\Helper\ContextHelper
        alias: admin_lte_theme.context_helper
        arguments:
            - '%admin_lte_theme.options%'
